# Generated by Django 3.1.7 on 2021-05-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210506_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(blank=True, choices=[('Square', 'Square'), ('Regular', 'Regular')], max_length=10),
        ),
    ]
