# Generated by Django 3.1.7 on 2021-05-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20210506_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Square', 'Square')], max_length=10),
        ),
    ]
